#cloud-config
package_update: true
package_upgrade: true
runcmd:
  # Install Docker
  - curl -fsSL https://get.docker.com -o get-docker.sh
  - sh get-docker.sh
  - usermod -aG docker azureuser
  - systemctl enable docker
  - systemctl start docker
  # Install Jenkins
  - apt update
  - apt install -y openjdk-11-jdk
  - wget -q -O - https://pkg.jenkins.io/debian/jenkins.io.key | apt-key add -
  - sh -c 'echo deb http://pkg.jenkins.io/debian-stable binary/ > /etc/apt/sources.list.d/jenkins.list'
  - apt update
  - apt install -y jenkins
  - systemctl enable jenkins
  - systemctl start jenkins
  # Print Jenkins initial admin password to log for easy access
  - echo "Jenkins initial admin password: $(cat /var/lib/jenkins/secrets/initialAdminPassword)"
